Create nodejs.yml
SamaraITCommunity/sitc-vk-parser pull request #12
Opened 2020-02-02 19:36 UTC by humb1t

2020-02-02 21:06 UTC, fax1ty commented on .github/workflows/nodejs.yml
> +    - run: npm run build --if-present
В скриптах не указана задача для build. Что оно будет делать?

2020-02-02 21:06 UTC, fax1ty commented on .github/workflows/nodejs.yml
> +    - run: npm test
Для test тоже

2020-02-02 21:07 UTC, fax1ty requested changes
В package.json нет задач build и test. При выполнении их ничего не произойдёт

2020-02-02 21:54 UTC, humb1t commented on .github/workflows/nodejs.yml
> +    - run: npm run build --if-present
понял, щас поправим

2020-02-03 07:44 UTC, fax1ty commented
@humb1t https://github.com/SamaraITCommunity/sitc-vk-parser/blob/3e568a1bb1fc748fdbf20ebbb7b4b2c722c0451c/package.json#L23-L25

Вот здесь должны быть скрипты для `build`. Что вообще должно делать `build`? В `start` уже `ts-node` собирает с помощью `tsc` JS сборку

2020-02-17 14:32 UTC, closed without merging